---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.5.3-jdk-8'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/ci/build.sh
